services:
  microservice_auth:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    # networks:
    #   - my-network
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo_auth:27017/authdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo_auth
    command: ["npm", "run", "dev"]

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    # networks:
    #   - my-network
    depends_on:
      - microservice_auth

  mongo_auth:
    container_name: mongo_auth 
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # networks:
    #   - my-network

volumes:
  mongo-data:
# networks:
#   my-network:
#     driver: bridge
