services:
  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    # networks:
    #   - my-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
    # networks:
    #   - my-network
    depends_on:
      - microservice

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # networks:
    #   - my-network

# networks:
#   my-network:
#     driver: bridge
